### ISSUE TITLE
Add units

### ISSUE THREAD

**Issue by stevenpitts** [makusu2/code-jam-5#20]
Speed should be in revolutions/min or whatever, score should be in something we decide like watts

**Comment by missingfragment** [comment]
Right now the internal value for speed is in degrees per frame, we could convert that to revolutions per minute with a formula.

**Comment by stevenpitts** [comment]
Added in https://github.com/makusu2/code-jam-5/pull/27/commits/ee07c883bbf02b3ecf26c692958cdaf91c6d0d99
