### ISSUE TITLE
Add tech tree

### ISSUE THREAD

**Issue by stevenpitts** [makusu2/code-jam-5#21]

**Comment by Foknetics** [comment]
Prices in tech tree should scale up to avoid getting to a point where power gained per second is out scaling cost of buying per second.

**Comment by stevenpitts** [comment]
Ideally it'd be like a screen that you can scroll through to see future options and whatever, but given our time limit, maybe the tech tree should be a static image (since there'll probably be no more than 8 total unlocks)?

**Comment by stevenpitts** [comment]
Closing as the code jam is over
