### ISSUE TITLE
Should we normalize element positions?

### ISSUE THREAD

**Issue by stevenpitts** [makusu2/code-jam-5#26]
Rather than saying `x=300, y=250`, in pixels, should we have x and y be unitless values from 0 to 1, representing their relative position on screen? Like, if I say `x=0.5` and the width of the screen is 640 pixels, it would go to 320. 
The issue with how it is now is that it feels too hardcodey

**Comment by missingfragment** [comment]
I second this.

**Comment by stevenpitts** [comment]
Added in https://github.com/makusu2/code-jam-5/pull/27/commits/f041e115f305623dda9909f90bc8c18915b4c8ee
