### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by missingfragment** [makusu2/code-jam-5#29]
I feel like 640 x 480 is kind of a strange resolution to use, we might be able to fit elements in more easily if we used something like 1280 x 720 or 1024 x 768.  Since we're using normalized positions now, changing it shouldn't be too difficult.  Does anyone have a good reason to keep using the resolution we have now?

**Comment by stevenpitts** [comment]
Nah, sounds good to me!

**Comment by stevenpitts** [comment]
Added in 255e309d593221f6a21c1ab29f40b42e0217ebcc
