### ISSUE TITLE
Save File?

### ISSUE THREAD

**Issue by missingfragment** [makusu2/code-jam-5#38]
We may want to have the game save your progress.  We could use gitignore to make sure the save file doesn't get put in the repository.  It would need to save the current score and number of machines and level of upgrades.

**Comment by stevenpitts** [comment]
I like the idea! Shouldn't be too hard! Did you want to do it, or can I take it on?

**Comment by stevenpitts** [comment]
Added in 06a36c8eb4ad5b549a18c2b18b2549f7879883e5
